### ISSUE TITLE
No source code in repository

### ISSUE THREAD

**Issue by zenminimoi** [Entrydo/swapcard-client#1]
Hi @JanMikes,

I can't see any code in this repo. 

Is it possible to upload it ?

Thank's !

**Comment by JanMikes** [comment]
Hello! It is currently not in project-decoupled state and it is reason why the repository is still empty :-).

I will try to decouple and share during this week. For now i can share source codes to this repository for inspiration if needed.

**Comment by zenminimoi** [comment]
Hi @JanMikes,

Thank you very much for you code :-)

I'll take a look on it.
